In [2]:
!pip install pandas
!pip install mysql-connector-python

Requirement already satisfied: pandas in d:\jupyet\lib\site-packages (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.1 in d:\jupyet\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\jupyet\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.18.5 in d:\jupyet\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: six>=1.5 in d:\jupyet\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Collecting mysql-connector-python
  Downloading mysql_connector_python-8.0.32-cp39-cp39-win_amd64.whl (7.9 MB)
     ---------------------------------------- 7.9/7.9 MB 5.8 MB/s eta 0:00:00
Collecting protobuf<=3.20.3,>=3.11.0
  Downloading protobuf-3.20.3-cp39-cp39-win_amd64.whl (904 kB)
     ------------------------------------- 904.2/904.2 kB 28.8 MB/s eta 0:00:00
Installing collected packages: protobuf, mysql-connector-python
Successfully installed mysql-connector-python-8.0.32 protobuf-3.20.3

In [3]:
import pandas as pd
import mysql.connector

In [4]:
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="Ligacampeon1",
  database="proyecto"
)

In [6]:
df_peru = pd.read_csv('D:\descargas\Matriculados_2016_al_2022.csv', delimiter=",")
df_peru

,Código,Año Matrícula,Período,Tipo de hecho,Género,Nacionalidad,Año Nacimiento,Departamento\nColegio,Distrito\nResidencia,Provincia\nResidencia,Departamento\nResidencia,Modalidad,Metodologia,Facultad,Especialidad,Ciclo Relativo
0,eb983f187c0f481be4aa97cbd3ce66139ff370a39bdbcf...,2016,1,REGULARES,MASCULINO,Peru,1967,LIMA,EL AGUSTINO,LIMA,LIMA,Pregrado,Presencial,"ARQUITECTURA, URBANISMO Y ARTES",ARQUITECTURA,10
1,000e2d0dcb4eaf37bb6851c82364f8fbff13edccac92c9...,2016,1,REGULARES,MASCULINO,Peru,1955,LIMA,CHACLACAYO,LIMA,LIMA,Pregrado,Presencial,INGENIERÍA ELÉCTRICA Y ELECTRÓNICA,INGENIERÍA ELÉCTRICA,9
2,fe34019137bdfad9083af4f91290e7bb1ed181006eedd7...,2016,1,REGULARES,MASCULINO,Peru,1970,LIMA,INDEPENDENCIA,LIMA,LIMA,Pregrado,Presencial,"INGENIERÍA ECONÓMICA, ESTADÍSTICA Y CIENCIAS S...",INGENIERÍA ECONÓMICA,2
3,133807cb215cc40e95f7ad419f8d4e0e15d5d631d9336e...,2016,1,REGULARES,MASCULINO,Peru,1971,LIMA,NaN,NaN,AMAZONAS,Pregrado,Presencial,INGENIERÍA ELÉCTRICA Y ELECTRÓNICA,INGENIERÍA ELECTRÓNICA,10
4,a0ae32c60ce68583f038569c807658c3a751c2a846dd17...,2016,1,REGULARES,MASCULINO,Peru,1957,LIMA,NaN,NaN,AMAZONAS,Pregrado,Presencial,INGENIERÍA ELÉCTRICA Y ELECTRÓNICA,INGENIERÍA ELECTRÓNICA,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163194,a6647c6c5b46f9bf3da5920c722f03250e04afc15c42cd...,2022,2,CACHIMBOS,MASCULINO,Peru,2004,LIMA,SAN JUAN DE LURIGANCHO,LIMA,LIMA,Pregrado,Presencial,CIENCIAS,INGENIERÍA FÍSICA,1
163195,7bfd981867bbc8f8b652378a9b8356314971edbc1e1fa9...,2022,2,CACHIMBOS,MASCULINO,Peru,2004,AREQUIPA,COMAS,LIMA,LIMA,Pregrado,Presencial,"INGENIERÍA ECONÓMICA, ESTADÍSTICA Y CIENCIAS S...",INGENIERÍA ESTADÍSTICA,1
163196,06f2fae0161128b546fde8d687ea007fbc9c5039287e5c...,2022,2,CACHIMBOS,MASCULINO,Peru,2004,LIMA,SAN JUAN DE MIRAFLORES,LIMA,LIMA,Pregrado,Presencial,CIENCIAS,QUÍMICA,1
163197,9e4ae56022abcdd37395f5ee8418ea32e9c41b523bcdc7...,2022,2,CACHIMBOS,FEMENINO,Peru,2004,LIMA,BREÑA,LIMA,LIMA,Pregrado,Presencial,"ARQUITECTURA, URBANISMO Y ARTES",ARQUITECTURA,1
163198,d4e3c646d90482fcbb1d13b11bf60f77c91ce577200c2e...,2022,2,CACHIMBOS,FEMENINO,Peru,1999,LIMA,ATE,LIMA,LIMA,Pregrado,Presencial,CIENCIAS,CIENCIA DE LA COMPUTACIÓN,1

In [7]:
# Crear una lista de valores para la nueva columna
valores_causas = list(range(1, 11)) + [None]*(len(df_peru)-10)

# Agregar la nueva columna al dataframe
df_peru['Causas'] = valores_causas

# Seleciona los datos entre 2018 y 2020
busqueda = df_peru.loc[df_peru['Año Matrícula'] >= 2018]
busqueda = busqueda.loc[df_peru['Año Matrícula'] <= 2021]

# Comenzar el indice en cero
busqueda = busqueda.reset_index(drop=True)

# Mostrar los datos selecionados
busqueda.isnull().sum()

Código                          0
Año Matrícula                   0
Período                         0
Tipo de hecho                   0
Género                         94
Nacionalidad                 1609
Año Nacimiento                  0
Departamento\nColegio        4180
Distrito\nResidencia        17703
Provincia\nResidencia       17418
Departamento\nResidencia     4869
Modalidad                       0
Metodologia                     0
Facultad                        0
Especialidad                    0
Ciclo Relativo                  0
Causas                      93452
dtype: int64

In [8]:
busqueda["Género"].fillna(value="N/A", inplace=True)
busqueda.isnull().sum()
#busqueda

Código                          0
Año Matrícula                   0
Período                         0
Tipo de hecho                   0
Género                          0
Nacionalidad                 1609
Año Nacimiento                  0
Departamento\nColegio        4180
Distrito\nResidencia        17703
Provincia\nResidencia       17418
Departamento\nResidencia     4869
Modalidad                       0
Metodologia                     0
Facultad                        0
Especialidad                    0
Ciclo Relativo                  0
Causas                      93452
dtype: int64

In [9]:
busqueda.loc[0:3, 'Causas'] = 'Factores Socioeconónicos'
busqueda.loc[4:100, 'Causas'] = 'Factores Institucionales'
busqueda.loc[101:2000, 'Causas'] = 'Factores Familiares'
busqueda.loc[2001:4000, 'Causas'] = 'Factores Sociales'
busqueda.loc[4001:6000, 'Causas'] = 'Factores Familiares'
busqueda.loc[6001:8000, 'Causas'] = 'Factores Personales'
busqueda.loc[8001:10000, 'Causas'] = 'Factores Psicológicos'
busqueda.loc[10001:23000, 'Causas'] = 'Factores Socioeconómicos'
busqueda.loc[23001:40000, 'Causas'] = 'Factores Psicológicos'
busqueda.loc[40001:60000, 'Causas'] = 'Factores Socioeconómicos'
busqueda.loc[60001:70818, 'Causas'] = 'Factores Familiares'
busqueda.loc[70819:93452, 'Causas'] = 'Factores Socioeconómicos'
busqueda

,Código,Año Matrícula,Período,Tipo de hecho,Género,Nacionalidad,Año Nacimiento,Departamento\nColegio,Distrito\nResidencia,Provincia\nResidencia,Departamento\nResidencia,Modalidad,Metodologia,Facultad,Especialidad,Ciclo Relativo,Causas
0,fa70233ca6e6e2b045256b70c2abf07457ea1375c12554...,2018,1,REGULARES,MASCULINO,Peru,1971,LIMA,SAN MARTIN DE PORRES,LIMA,LIMA,Pregrado,Presencial,"ARQUITECTURA, URBANISMO Y ARTES",ARQUITECTURA,9,Factores Socioeconónicos
1,1cbf58670318b151fe9c1c4bf80a46db4bc6b9ff817c63...,2018,1,REGULARES,MASCULINO,Peru,1975,LIMA,SAN MARTIN DE PORRES,LIMA,LIMA,Pregrado,Presencial,"ARQUITECTURA, URBANISMO Y ARTES",ARQUITECTURA,10,Factores Socioeconónicos
2,681b437818b5f6c69823ca05a53ce328bdf4b2a373c33f...,2018,1,PROMOCION,MASCULINO,Peru,1972,UCAYALI,LOS OLIVOS,LIMA,LIMA,Pregrado,Presencial,INGENIERÍA ELÉCTRICA Y ELECTRÓNICA,INGENIERÍA ELÉCTRICA,6,Factores Socioeconónicos
3,2a25a422755105b36c75fdc25709b7e4033b1c2fb4be14...,2018,1,REGULARES,MASCULINO,Peru,1974,LIMA,COMAS,LIMA,LIMA,Pregrado,Presencial,INGENIERÍA CIVIL,INGENIERÍA CIVIL,2,Factores Socioeconónicos
4,eb7713c8893828a5eea0b39c15688c709f621dd2043ebd...,2018,1,REGULARES,MASCULINO,Peru,1963,NaN,NaN,NaN,NaN,Pregrado,Presencial,INGENIERÍA CIVIL,INGENIERÍA CIVIL,3,Factores Institucionales
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93447,6f3243e0189d47679ade80d4061bd8e703f3aba434535a...,2021,2,PROMOCION,MASCULINO,Peru,1999,PUNO,NaN,NaN,AMAZONAS,Pregrado,Presencial,INGENIERÍA CIVIL,INGENIERÍA CIVIL,10,Factores Socioeconómicos
93448,fd1cd6113e9e08eb33d8139e442f063247ef1e0b2837b4...,2021,2,REGULARES,MASCULINO,Peru,1998,LIMA,LOS OLIVOS,LIMA,LIMA,Pregrado,Presencial,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA DE SISTEMAS,6,Factores Socioeconómicos
93449,e3666c8319339046b7df1796f0b87fb71f39403dd73633...,2021,2,REGULARES,MASCULINO,Peru,2000,LIMA,LIMA,LIMA,LIMA,Pregrado,Presencial,INGENIERÍA INDUSTRIAL Y DE SISTEMAS,INGENIERÍA INDUSTRIAL,7,Factores Socioeconómicos
93450,49159cf9c28dc55a1521afc8b0d0b5be5158e95c08bffa...,2021,2,REGULARES,MASCULINO,Peru,2001,HUANCAVELICA,HUANCAVELICA,HUANCAVELICA,HUANCAVELICA,Pregrado,Presencial,INGENIERÍA MECÁNICA,INGENIERÍA MECÁNICA Y ELÉCTRICA,8,Factores Socioeconómicos
93451,9f65b1c8b1b8a5355a70bad83757086581270468f12440...,2021,2,REGULARES,MASCULINO,Peru,1999,LIMA,NaN,NaN,NaN,Pregrado,Presencial,"INGENIERÍA GEOLÓGICA, MINERA Y METALÚRGICA",INGENIERÍA GEOLÓGICA,9,Factores Socioeconómicos

In [11]:
direccion_servidor = 'localhost'
nombre_bd = 'proyecto'
nombre_usuario = 'root'
password = 'Ligacampeon1'

In [19]:
try:
    # Conectar a la base de datos
    conexion = mysql.connector.connect(
        host=direccion_servidor,
        database=nombre_bd,
        user=nombre_usuario,
        password=password
    )

    # Obtener un cursor para interactuar con la base de datos
    cursor = conexion.cursor()

    # Iterar sobre el DataFrame e insertar los datos en la tabla
    for index, row in busqueda.iterrows():
        cursor.execute("INSERT INTO Datos_Peru (Anio_Matricula,Periodo,Tipo_hecho,Genero,Causas) VALUES (%s,%s,%s,%s,%s)", (row['Año Matrícula'], row['Período'], row['Tipo de hecho'], row['Género'], row['Causas']))

    # Confirmar los cambios
    conexion.commit()
    print("Datos insertados correctamente")

except Exception as e:
    # Atrapar error
    print("Ocurrió un error al insertar los datos: ", e)

Datos insertados correctamente

In [20]:
query = "SELECT * FROM Datos_Peru"
datos_peru= pd.read_sql_query(query, conexion)
datos_peru

D:\jupyet\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

        Anio_Matricula Periodo Tipo_hecho     Genero                    Causas
0                 2018       1  REGULARES  MASCULINO  Factores Socioeconónicos
1                 2018       1  REGULARES  MASCULINO  Factores Socioeconónicos
2                 2018       1  PROMOCION  MASCULINO  Factores Socioeconónicos
3                 2018       1  REGULARES  MASCULINO  Factores Socioeconónicos
4                 2018       1  REGULARES  MASCULINO  Factores Institucionales
...                ...     ...        ...        ...                       ...
186899            2021       2  PROMOCION  MASCULINO  Factores Socioeconómicos
186900            2021       2  REGULARES  MASCULINO  Factores Socioeconómicos
186901            2021       2  REGULARES  MASCULINO  Factores Socioeconómicos
186902            2021       2  REGULARES  MASCULINO  Factores Socioeconómicos
186903            2021       2  REGULARES  MASCULINO  Factores Socioeconómicos

[186904 rows x 5 columns]

In [21]:
datos_peru.to_csv("DatosLimpios_Peru.csv")

In [22]:
conexion.close()